### ISSUE TITLE
Since we are only applying the styling to one HTML element...

### ISSUE THREAD

**Issue by jzhu01** [middleduck/prj-rev-bwfs-dasmoto#1]
It might make more sense to use an ID than a class on the h2s. 

See example line: https://github.com/middleduck/prj-rev-bwfs-dasmoto/blob/master/Dasmatos%20-%20Project%201/index.html#L9

**Comment by middleduck** [comment]
Could you explain why?

**Comment by jzhu01** [comment]
Sure, so it's because the h2s really are only having one thing changed between them, and that is the background color. Rather than use a class, which implies we're going to give the class to multiple HTML elements, it would make more sense to use an ID, which is unique to every element.
