### ISSUE TITLE
font-weight:bold on h1 and h2s do not affect display!

### ISSUE THREAD

**Issue by jzhu01** [middleduck/prj-rev-bwfs-dasmoto#2]
See line: https://github.com/middleduck/prj-rev-bwfs-dasmoto/blob/master/Dasmatos%20-%20Project%201/Resources/CSS/style.css#L7

Adding a font-weight:bold on the h1 and h2s does not change how the header's appearance.

**Comment by middleduck** [comment]
Is that because they are bold by default?

**Comment by jzhu01** [comment]
Correct! :D
