### ISSUE TITLE
Extra html selector that is empty should be removed, or replaced by list of selectors for font-family

### ISSUE THREAD

**Issue by jzhu01** [middleduck/prj-rev-bwfs-dasmoto#3]
I noticed you have this: https://github.com/middleduck/prj-rev-bwfs-dasmoto/blob/master/Dasmatos%20-%20Project%201/Resources/CSS/style.css#L1-L3

You could either set the font-family once in there, or change it to be a list of selectors (i.e. h1, h2, h3, p) and then set the font-family once. It's just repeated so often, the line (https://github.com/middleduck/prj-rev-bwfs-dasmoto/blob/master/Dasmatos%20-%20Project%201/Resources/CSS/style.css#L5) you could clean up your code by adding it in only once.

**Comment by middleduck** [comment]
It slipped my mind to use that.  Will keep in mind to look out for code at top level instead of repeating it at each element.
