### ISSUE TITLE
No need to use both strong and font-weight:bold, alternative to links

### ISSUE THREAD

**Issue by jzhu01** [middleduck/prj-rev-bwfs-dasmoto#4]
See line: https://github.com/middleduck/prj-rev-bwfs-dasmoto/blob/master/Dasmatos%20-%20Project%201/index.html#L13

Here there's no need to have a strong tag because you font-weight:bold on link. Speaking of links, it might be better to implement a span, since the link does not have an href source.

**Comment by middleduck** [comment]
Hi Jen, not sure what you mean by 'span'.  Also, are you able to give an example of how you would have wrote the line of code?

**Comment by jzhu01** [comment]
Sure, so instead of doing it as you have done, I would recommend something using the span tag, so something like this: 
`<p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="price">Starting at $3.00 / brush.</span></p>`

Hope that makes sense!
